backend:
  name: git-gateway  # Authentication method (using GitHub login)
  branch: main       # Set the branch (main or master)

media_folder: "/"   # Media folder for image uploads
public_folder: "/"        # Public path for the media

collections:
  - name: "notices"   # Collection name (for notices)
    label: "Notices"   # Display name in CMS
    folder: "notices"  # Folder where the markdown files are stored
    create: true       # Allow creation of new notices
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"   # Slug format
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "content", widget: "markdown" }
