backend:
  name: git-gateway
  branch: main  # or "master" depending on your Git branch

media_folder: "assets/images"  # Folder for uploaded media (e.g., images)
public_folder: "/images"  # Public URL for media

collections:
  - name: "notices"  # Collection name
    label: "Notices"  # Display name in the CMS
    folder: "notices"  # Folder where notice files are stored (in this case, Markdown files)
    create: true  # Allow creating new notices
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Slug format for filenames (e.g., "2024-11-17-school-reopening")
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "content", widget: "text" }
