backend:
  name: "github" # or any other backend like "gitlab", "database", etc.
  branch: "main"  # Specify the branch name if using a git-based CMS.

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

media_folder: "static/media"  # Folder for media files.
media_library:
  name: "local"  # Type of media library (could be "local", "cloudinary", etc.)
  label: "Local Media Library"
  field: "image"  # Name of the field used for images/media.
